name: PowerNukkitX

on: [push,pull_request]

jobs:
  check-files:
    name: 检查仓库文件
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.check-changed-files.outputs.all_changed_and_modified_files }}

    steps:
      - name: 检出仓库内容
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 检查文件改动情况
        id: check-changed-files
        uses: tj-actions/changed-files@v11.4

      - name: 输出更改文件列表
        run: echo ${{ steps.check-changed-files.outputs.all_changed_and_modified_files }}

  build-server:
    name: 构建PNX服务端
    runs-on: ubuntu-latest
    needs: check-files
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && (contains(needs.check-files.outputs.changed-files, 'src/') || (github.event_name == 'push' && contains(github.event.commits[0].message, '+b')))

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package -DskipTests=false -Darguments="-Dmaven.javadoc.skip=true"
      - name: Rename artifacts
        run: |
          mv target/powernukkitx-*-SNAPSHOT.jar target/powernukkitx.jar
          mv target/powernukkitx-*-SNAPSHOT-shaded.jar target/powernukkitx-full.jar
      - name: Archive PNX Core
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-Core
          path: target/powernukkitx.jar
      - name: Archive PNX Full
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-Full
          path: target/powernukkitx-full.jar
      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-Libs
          path: target/libs/
      - name: Get Short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Upload to OSS
        uses: tvrcgo/upload-to-oss@v0.1.1
        if: github.event_name == 'push' && github.repository == 'PowerNukkitX/PowerNukkitX' && (!contains(github.ref_name, 'patch'))
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-hongkong
          bucket: pnx-assets
          asset-path: ./target/powernukkitx.jar
          target-path: /core/${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}/
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        if: github.repository == 'PowerNukkitX/PowerNukkitX' && (!contains(github.ref_name, 'patch'))
        with:
          timeZone: 8
          format: 'YYYY/MM/DD-HH:mm:ss'
      - name: Update MineBBS info
        uses: fjogeleit/http-request-action@v1
        if: github.event_name == 'push' && github.repository == 'PowerNukkitX/PowerNukkitX' && (!contains(github.ref_name, 'patch'))
        with:
          url: 'https://api.minebbs.com/api/openapi/v1/resources/3668/update'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.MINEBBS_API_KEY }}"}'
          contentType: 'application/json'
          data: '{"title": "${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}", "description": "${{ github.event.commits[0].message }}", "new_version": "${{ steps.time.outputs.time }}", "file_url": "https://ci.lt-name.cn/job/PowerNukkitX/"}'
          escapeData: 'true'

  build-bootstrap:
    name: 构建启动器
    runs-on: ubuntu-latest
    needs: check-files
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && (contains(needs.check-files.outputs.changed-files, 'Bootstrap/src/') || (github.event_name == 'push' && contains(github.event.commits[0].message, '+b')))

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B -f Bootstrap/pom.xml package -DskipTests=false -Darguments="-Dmaven.javadoc.skip=true"
      - name: Rename artifacts
        run: mv Bootstrap/target/Bootstrap-*-shaded.jar Bootstrap/target/bootstrap.jar
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-bootstrap
          path: Bootstrap/target/bootstrap.jar
      - name: Get Short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Upload to OSS
        uses: tvrcgo/upload-to-oss@v0.1.1
        if: github.event_name == 'push' && github.repository == 'PowerNukkitX/PowerNukkitX' && (!contains(github.ref_name, 'patch'))
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-hongkong
          bucket: pnx-assets
          asset-path: ./Bootstrap/target/bootstrap.jar
          target-path: /bootstrap/${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}/
